version: "3"
services:
  trading-app:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
    depends_on:
      - db
    env_file:
      - ./server/.env
    command: npm run start

  db:
    image: mongo
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
