version: "3"
services:
  trading-app:
    build: ./server
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
    depends_on:
      - db
    environment:
      DB_CONNECTION_STRING: mongodb://db:27017/mydatabase
    command: npm run start

  db:
    image: mongo
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
